import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapClient from "../Components/bootstrap";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Script
          src="https://kit.fontawesome.com/9ce934e231.js"
          crossorigin="anonymous"
        ></Script>
            <BootstrapClient/>
      </body>
    </html>
  );
}
